import type { IssuanceConfig } from "./config.js";

function str(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
}

/**
 * Generate the stellar.toml content for an issued asset. Serve it at
 * https://<homeDomain>/.well-known/stellar.toml with CORS enabled.
 */
export function generateToml(config: IssuanceConfig): string {
  const t = config.toml;
  if (!t || !config.homeDomain) throw new Error("toml info and homeDomain are required");
  const lines = [
    "# Generated by assetforge",
    `NETWORK_PASSPHRASE=${str(config.network === "public" ? "Public Global Stellar Network ; September 2015" : "Test SDF Network ; September 2015")}`,
    `ACCOUNTS=[${str(config.issuer)}]`,
    "",
    "[DOCUMENTATION]",
    `ORG_NAME=${str(t.orgName)}`,
    `ORG_URL=${str(t.orgUrl)}`,
    ...(t.orgSupportEmail ? [`ORG_SUPPORT_EMAIL=${str(t.orgSupportEmail)}`] : []),
    "",
    "[[CURRENCIES]]",
    `code=${str(config.code)}`,
    `issuer=${str(config.issuer)}`,
    `name=${str(t.name)}`,
    `desc=${str(t.desc)}`,
    ...(t.image ? [`image=${str(t.image)}`] : []),
    `display_decimals=7`,
    `is_asset_anchored=${t.anchorAssetType && t.anchorAssetType !== "other" ? "true" : "false"}`,
    ...(t.anchorAssetType ? [`anchor_asset_type=${str(t.anchorAssetType)}`] : []),
    ...(config.lockIssuer ? [`fixed_number=${config.supply}`] : []),
    `is_unlimited=${config.lockIssuer ? "false" : "true"}`,
    "",
  ];
  return lines.join("\n");
}
